# Generated by Django 4.1 on 2023-04-20 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sejong",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("cate1", models.CharField(max_length=50)),
                ("cate2", models.CharField(max_length=50)),
                ("cate3", models.CharField(max_length=50)),
                ("catemix", models.CharField(max_length=50)),
                ("lon", models.FloatField(max_length=20)),
                ("lat", models.FloatField(max_length=20)),
                ("type", models.CharField(max_length=20, null=True)),
                ("star", models.FloatField(max_length=5, null=True)),
                ("review_ori", models.CharField(max_length=3000)),
                ("keyword", models.CharField(max_length=200)),
                ("review", models.CharField(max_length=2000)),
                ("positive", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "DAEGU",
                "managed": False,
            },
        ),
    ]
