# Generated by Django 4.1 on 2023-04-20 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="daegu",
            table="daegu",
        ),
    ]
